#!/bin/bash

[ $# -ne 2 ] && exit 40

[ "$1" == '' ] && exit 41

[ "$2" == '' ] && exit 42

USER=`/usr/xpg4/bin/id -un`
[ "$USER" == '' ] && exit 43

LOGFILE=/tmp/`basename $0`.$USER.$$.log
OLDFNAME=$1
NEWFNAME=$2
CP=/usr/bin/cp

$CP $OLDFNAME $NEWFNAME

if [ "$?" -ne 0 ]
then
  echo "$CP $OLDFNAME $NEWFNAME failed" >> $LOGFILE
  exit 44
fi

exit 0
