#!/bin/bash

# get program name
[ -f "/usr/bin/basename" ] && BASENAME=/usr/bin/basename
[ -f "/bin/basename" ] && BASENAME=/bin/basename
pgm=`$BASENAME "$0"`

# init cmds used in this script
CAT=/bin/cat

# check existence of binaries (thanks NASOM)
for i in $CAT
do
        [ ! -f "$i" ] && $ECHO "ERROR: $pgm failed (missing cmd)" && echo "cmd: $i" && exit 1
done

# verify arg passed correctly and is valid
[ $# -ne 1 -o ! -e "$1" ] && $ECHO "ERROR: $pgm failed (arg invalid)" && exit 1

# init vars
path="$1"

$CAT $path 
[ $? -ne 0 ] && exit 1

exit 0
